### ISSUE TITLE
Unhandled error after several re-renders (going from 0.62.0 to 0.63.0)

### ISSUE THREAD

**Issue by onionhammer** [plouc/nivo#1170]
This issue didn't exist in 0.62, only noticed after upgrading to 0.63, and it goes away after downgrading:

![image](https://user-images.githubusercontent.com/969938/96646735-35448280-12f2-11eb-95e4-6e5a3722c0ef.png)

Changing the data attribute several times seems to produce this issue, but the exception is deep down the stack.

Please let me know if this issue isn't an obvious fix and I will create a codesandbox to reproduce it.

**Comment by wyze** [comment]
> Please let me know if this issue isn't an obvious fix and I will create a codesandbox to reproduce it.

A codesandbox would be much appreciated please!

**Comment by wyze** [comment]
I was able to reproduce this using nivo's website. It is an issue with how we are using react-spring. I'll have to dig in and take a look.

**Comment by onionhammer** [comment]
I was just about to dig into a codesandbox, but I'll hold off!

**Comment by stephent** [comment]
Some other variants of what I think is a similar problem observed in Sentry error logs (in addition to @onionhammer's example which I also observed):

`TypeError
undefined is not an object (evaluating 'n[e].push')`

Crashed in non-app: ../node_modules/react-spring/web.js

and 

`TypeError: n[e] is undefined
  at forEach(../node_modules/react-spring/web.js:1854:43)
  at forEach(../node_modules/react-spring/web.js:1854:35)
  at interpolation(../node_modules/react-spring/web.js:1853:15)
  at createInterpolator(../node_modules/react-spring/web.js:454:12)
  at updateConfig(../node_modules/react-spring/web.js:512:17)
  at reduce(../node_modules/react-spring/web.js:971:33)
  at diff(../node_modules/react-spring/web.js:922:51)
  at forEach(../node_modules/react-spring/web.js:822:62)
  at start(../node_modules/react-spring/web.js:800:13)
  at map(../node_modules/react-spring/web.js:1113:17)
  at updateCtrl(../node_modules/react-spring/web.js:1111:64)
  at d(../node_modules/react-spring/web.js:1118:18)
  at Ii(../node_modules/react-dom/cjs/react-dom.production.min.js:211:320)`

These occurred after updating from 0.62.0 to 0.63.0 and haven't recurred since downgrading. I haven't been able to reproduce myself yet - these are from user crash reports.
