### ISSUE TITLE
0.79 regression: Yarn 3 berry errors with @nivo/legends dependencies (d3-scale and @nivo/colors)

### ISSUE THREAD

**Issue by davidcalhoun** [plouc/nivo#1951]
**Describe/explain the bug**
Using `@nivo/legends` in a project with Webpack and Yarn 3 berry results in these errors in `@nivo/legends`:

- `ModuleNotFoundError: Module not found: Error: Can't resolve '@nivo/colors'...` ... `@nivo/legends tried to access @nivo/colors, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.`
- `ModuleNotFoundError: Module not found: Error: Can't resolve 'd3-scale'...` ... `@nivo/legends tried to access d3-scale, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.`

I'm able to compile without errors in the previous version 0.78.  It looks like as of 0.79, `d3-scale` and `@nivo/colors` are [now being used in the code](https://github.com/plouc/nivo/blob/v0.79.0/packages/legends/src/compute.ts#L1).  [These two dependencies have been added to devDependencies](https://github.com/plouc/nivo/blob/v0.79.0/packages/legends/package.json#L27) but since they run in production they should instead be added to `dependencies`, which will clear up the Yarn/Webpack error.  I was able to confirm this by adding a temporary Yarn `packageExtensions` workaround in `.yarnrc.yml`:

```yml
# .yarnrc.yml

...

packageExtensions:
    '@nivo/legends@*':
        dependencies:
            'd3-scale': '*'
            '@nivo/colors': '*'
...

```

Adding this and then rerunning `yarn` works as a temporary workaround.

**To Reproduce**
Create a new project using Yarn 3 and Webpack 5.  Use a Nivo Bar chart that uses a legend and then try to compile the project.  In the case above I'm using Storybook, which uses Webpack 5 under the hood.

**Expected behavior**
I expect Webpack to compile without errors.

**Screenshots**
Full error:

```
ModuleNotFoundError: Module not found: Error: Can't resolve 'd3-scale' in '/Users/dcalhoun/dev/[REDACTED]/.yarn/__virtual__/@nivo-legends-virtual-a3300eb7f3/0/cache/@nivo-legends-npm-0.79.1-dd1c63aa09-1f4bb8da28.zip/node_modules/@nivo/legends/dist'
    at /Users/dcalhoun/dev/[REDACTED]/.yarn/__virtual__/webpack-virtual-083a0157ef/0/cache/webpack-npm-5.69.1-e85947ca9d-490a6e9e4c.zip/node_modules/webpack/lib/Compilation.js:2014:28
    at /Users/dcalhoun/dev/[REDACTED]/.yarn/__virtual__/webpack-virtual-083a0157ef/0/cache/webpack-npm-5.69.1-e85947ca9d-490a6e9e4c.zip/node_modules/webpack/lib/NormalModuleFactory.js:791:13
    at eval (eval at create (/Users/dcalhoun/dev/[REDACTED]/.yarn/cache/tapable-npm-2.2.1-8cf5ff3039-3b7a1b4d86.zip/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/dcalhoun/dev/[REDACTED]/.yarn/__virtual__/webpack-virtual-083a0157ef/0/cache/webpack-npm-5.69.1-e85947ca9d-490a6e9e4c.zip/node_modules/webpack/lib/NormalModuleFactory.js:265:22
    at eval (eval at create (/Users/dcalhoun/dev/[REDACTED]/.yarn/cache/tapable-npm-2.2.1-8cf5ff3039-3b7a1b4d86.zip/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/dcalhoun/dev/[REDACTED]/.yarn/__virtual__/webpack-virtual-083a0157ef/0/cache/webpack-npm-5.69.1-e85947ca9d-490a6e9e4c.zip/node_modules/webpack/lib/NormalModuleFactory.js:427:22
    at /Users/dcalhoun/dev/[REDACTED]/.yarn/__virtual__/webpack-virtual-083a0157ef/0/cache/webpack-npm-5.69.1-e85947ca9d-490a6e9e4c.zip/node_modules/webpack/lib/NormalModuleFactory.js:111:11
    at /Users/dcalhoun/dev/[REDACTED]/.yarn/__virtual__/webpack-virtual-083a0157ef/0/cache/webpack-npm-5.69.1-e85947ca9d-490a6e9e4c.zip/node_modules/webpack/lib/NormalModuleFactory.js:663:25
    at /Users/dcalhoun/dev/[REDACTED]/.yarn/__virtual__/webpack-virtual-083a0157ef/0/cache/webpack-npm-5.69.1-e85947ca9d-490a6e9e4c.zip/node_modules/webpack/lib/NormalModuleFactory.js:848:8
    at /Users/dcalhoun/dev/[REDACTED]/.yarn/__virtual__/webpack-virtual-083a0157ef/0/cache/webpack-npm-5.69.1-e85947ca9d-490a6e9e4c.zip/node_modules/webpack/lib/NormalModuleFactory.js:968:5
    at /Users/dcalhoun/dev/[REDACTED]/.yarn/cache/neo-async-npm-2.6.2-75d6902586-deac9f8d00.zip/node_modules/neo-async/async.js:6883:13
    at /Users/dcalhoun/dev/[REDACTED]/.yarn/__virtual__/webpack-virtual-083a0157ef/0/cache/webpack-npm-5.69.1-e85947ca9d-490a6e9e4c.zip/node_modules/webpack/lib/NormalModuleFactory.js:951:45
    at finishWithoutResolve (/Users/dcalhoun/dev/[REDACTED]/.yarn/cache/enhanced-resolve-npm-5.9.1-9fd94589cf-d5adf8fa8b.zip/node_modules/enhanced-resolve/lib/Resolver.js:312:11)
    at /Users/dcalhoun/dev/[REDACTED]/.yarn/cache/enhanced-resolve-npm-5.9.1-9fd94589cf-d5adf8fa8b.zip/node_modules/enhanced-resolve/lib/Resolver.js:386:15
    at /Users/dcalhoun/dev/[REDACTED]/.yarn/cache/enhanced-resolve-npm-5.9.1-9fd94589cf-d5adf8fa8b.zip/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/dcalhoun/dev/[REDACTED]/.yarn/cache/tapable-npm-2.2.1-8cf5ff3039-3b7a1b4d86.zip/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
resolve 'd3-scale' in '/Users/dcalhoun/dev/[REDACTED]/.yarn/__virtual__/@nivo-legends-virtual-a3300eb7f3/0/cache/@nivo-legends-npm-0.79.1-dd1c63aa09-1f4bb8da28.zip/node_modules/@nivo/legends/dist'
  Parsed request is a module
  using description file: /Users/dcalhoun/dev/[REDACTED]/.yarn/__virtual__/@nivo-legends-virtual-a3300eb7f3/0/cache/@nivo-legends-npm-0.79.1-dd1c63aa09-1f4bb8da28.zip/node_modules/@nivo/legends/package.json (relative path: ./dist)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      request is not managed by the pnpapi
        @nivo/legends tried to access d3-scale, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
        Required package: d3-scale
        Required by: @nivo/legends@virtual:888f7fcac72d11930aeb4fe441c94c746f1941a2f41ba75aa661170163646568d6fa45f4cb04a9df4aa9d63836d2b072cd115b0c7a3ed170008cb5a67e712807#npm:0.79.1 (via /Users/dcalhoun/dev/[REDACTED]/.yarn/__virtual__/@nivo-legends-virtual-a3300eb7f3/0/cache/@nivo-legends-npm-0.79.1-dd1c63aa09-1f4bb8da28.zip/node_modules/@nivo/legends/dist/)
ModuleNotFoundError: Module not found: Error: Can't resolve '@nivo/colors' in '/Users/dcalhoun/dev/[REDACTED]/.yarn/__virtual__/@nivo-legends-virtual-a3300eb7f3/0/cache/@nivo-legends-npm-0.79.1-dd1c63aa09-1f4bb8da28.zip/node_modules/@nivo/legends/dist'
    at /Users/dcalhoun/dev/[REDACTED]/.yarn/__virtual__/webpack-virtual-083a0157ef/0/cache/webpack-npm-5.69.1-e85947ca9d-490a6e9e4c.zip/node_modules/webpack/lib/Compilation.js:2014:28
    at /Users/dcalhoun/dev/[REDACTED]/.yarn/__virtual__/webpack-virtual-083a0157ef/0/cache/webpack-npm-5.69.1-e85947ca9d-490a6e9e4c.zip/node_modules/webpack/lib/NormalModuleFactory.js:791:13
    at eval (eval at create (/Users/dcalhoun/dev/[REDACTED]/.yarn/cache/tapable-npm-2.2.1-8cf5ff3039-3b7a1b4d86.zip/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Users/dcalhoun/dev/[REDACTED]/.yarn/__virtual__/webpack-virtual-083a0157ef/0/cache/webpack-npm-5.69.1-e85947ca9d-490a6e9e4c.zip/node_modules/webpack/lib/NormalModuleFactory.js:265:22
    at eval (eval at create (/Users/dcalhoun/dev/[REDACTED]/.yarn/cache/tapable-npm-2.2.1-8cf5ff3039-3b7a1b4d86.zip/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Users/dcalhoun/dev/[REDACTED]/.yarn/__virtual__/webpack-virtual-083a0157ef/0/cache/webpack-npm-5.69.1-e85947ca9d-490a6e9e4c.zip/node_modules/webpack/lib/NormalModuleFactory.js:427:22
    at /Users/dcalhoun/dev/[REDACTED]/.yarn/__virtual__/webpack-virtual-083a0157ef/0/cache/webpack-npm-5.69.1-e85947ca9d-490a6e9e4c.zip/node_modules/webpack/lib/NormalModuleFactory.js:111:11
    at /Users/dcalhoun/dev/[REDACTED]/.yarn/__virtual__/webpack-virtual-083a0157ef/0/cache/webpack-npm-5.69.1-e85947ca9d-490a6e9e4c.zip/node_modules/webpack/lib/NormalModuleFactory.js:663:25
    at /Users/dcalhoun/dev/[REDACTED]/.yarn/__virtual__/webpack-virtual-083a0157ef/0/cache/webpack-npm-5.69.1-e85947ca9d-490a6e9e4c.zip/node_modules/webpack/lib/NormalModuleFactory.js:848:8
    at /Users/dcalhoun/dev/[REDACTED]/.yarn/__virtual__/webpack-virtual-083a0157ef/0/cache/webpack-npm-5.69.1-e85947ca9d-490a6e9e4c.zip/node_modules/webpack/lib/NormalModuleFactory.js:968:5
    at /Users/dcalhoun/dev/[REDACTED]/.yarn/cache/neo-async-npm-2.6.2-75d6902586-deac9f8d00.zip/node_modules/neo-async/async.js:6883:13
    at /Users/dcalhoun/dev/[REDACTED]/.yarn/__virtual__/webpack-virtual-083a0157ef/0/cache/webpack-npm-5.69.1-e85947ca9d-490a6e9e4c.zip/node_modules/webpack/lib/NormalModuleFactory.js:951:45
    at finishWithoutResolve (/Users/dcalhoun/dev/[REDACTED]/.yarn/cache/enhanced-resolve-npm-5.9.1-9fd94589cf-d5adf8fa8b.zip/node_modules/enhanced-resolve/lib/Resolver.js:312:11)
    at /Users/dcalhoun/dev/[REDACTED]/.yarn/cache/enhanced-resolve-npm-5.9.1-9fd94589cf-d5adf8fa8b.zip/node_modules/enhanced-resolve/lib/Resolver.js:386:15
    at /Users/dcalhoun/dev/[REDACTED]/.yarn/cache/enhanced-resolve-npm-5.9.1-9fd94589cf-d5adf8fa8b.zip/node_modules/enhanced-resolve/lib/Resolver.js:435:5
    at eval (eval at create (/Users/dcalhoun/dev/[REDACTED]/.yarn/cache/tapable-npm-2.2.1-8cf5ff3039-3b7a1b4d86.zip/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
resolve '@nivo/colors' in '/Users/dcalhoun/dev/[REDACTED]/.yarn/__virtual__/@nivo-legends-virtual-a3300eb7f3/0/cache/@nivo-legends-npm-0.79.1-dd1c63aa09-1f4bb8da28.zip/node_modules/@nivo/legends/dist'
  Parsed request is a module
  using description file: /Users/dcalhoun/dev/[REDACTED]/.yarn/__virtual__/@nivo-legends-virtual-a3300eb7f3/0/cache/@nivo-legends-npm-0.79.1-dd1c63aa09-1f4bb8da28.zip/node_modules/@nivo/legends/package.json (relative path: ./dist)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      request is not managed by the pnpapi
        @nivo/legends tried to access @nivo/colors, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
        Required package: @nivo/colors
        Required by: @nivo/legends@virtual:888f7fcac72d11930aeb4fe441c94c746f1941a2f41ba75aa661170163646568d6fa45f4cb04a9df4aa9d63836d2b072cd115b0c7a3ed170008cb5a67e712807#npm:0.79.1 (via /Users/dcalhoun/dev/[REDACTED]/.yarn/__virtual__/@nivo-legends-virtual-a3300eb7f3/0/cache/@nivo-legends-npm-0.79.1-dd1c63aa09-1f4bb8da28.zip/node_modules/@nivo/legends/dist/)
```

**Desktop (please complete the following information):**
 - OS: macOS 11.6
 - Browser N/A
 - Version N/A

**Comment by davidcalhoun** [comment]
This is related to #1941 but with added details - I'm ok if you want to close this in favor of that ticket.

**Comment by mihiretkiflu** [comment]
bump

**Comment by plouc** [comment]
I'm trying to address this issue in https://github.com/plouc/nivo/pull/2313.
