### ISSUE TITLE
Website and charts not loading in Brave (without any ad-blocking

### ISSUE THREAD

**Issue by mortenhjort** [plouc/nivo#1974]
**Describe/explain the bug**
The website is blank when visiting using Brave (MacOS). Tested with and without the Braves blocking mechanism with the same result. Unsure if this is a bug our users can expect if they visit our (future) use of Nivo Charts.

**To Reproduce**
Download https://brave.com and visit https://nivo.rocks/

If you reload using CMD + Shift + R the site will show, but if you update normally it will be blank again. A reload with the SHIFT key will again make it work and so forth. 

Empty Cache has not provided a proper solution.

 - OS: MacOS Monterey 12.3.1
 - Browser: Brave
 - Version: 1.37.111 (Arm)

**Comment by revolunet** [comment]
same issue on OSX + Chrome 100.0.4896.127 

<img width="781" alt="Capture d’écran 2022-04-23 à 23 56 32" src="https://user-images.githubusercontent.com/124937/164947282-0df5abca-1c22-48db-83f7-72fea28dda82.png">

**Comment by matthewoates** [comment]
Getting a white screen of death in the latest chrome with no extensions:

```
react-dom.production.min.js:216 Error: The result of this StaticQuery could not be fetched.

This is likely a bug in Gatsby and if refreshing the page does not fix it, please open an issue in https://github.com/gatsbyjs/gatsby/issues
    at p (gatsby-browser-entry.js:77:11)
    at c (Seo.tsx:20:22)
    at ro (react-dom.production.min.js:157:137)
    at Hu (react-dom.production.min.js:267:460)
    at Pi (react-dom.production.min.js:250:347)
    at _i (react-dom.production.min.js:250:278)
    at xi (react-dom.production.min.js:250:138)
    at vi (react-dom.production.min.js:243:163)
    at fi (react-dom.production.min.js:237:175)
    at Gi (react-dom.production.min.js:285:27)
uu @ react-dom.production.min.js:216
a.componentDidCatch.n.callback @ react-dom.production.min.js:217
fa @ react-dom.production.min.js:131
hu @ react-dom.production.min.js:220
Li @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wl @ react-dom.production.min.js:122
Ti @ react-dom.production.min.js:252
vi @ react-dom.production.min.js:243
fi @ react-dom.production.min.js:237
Gi @ react-dom.production.min.js:285
(anonymous) @ react-dom.production.min.js:289
yi @ react-dom.production.min.js:244
rs @ react-dom.production.min.js:289
t.hydrate @ react-dom.production.min.js:295
c @ production-app.js:209
(anonymous) @ production-app.js:221
setTimeout (async)
(anonymous) @ production-app.js:220
Promise.then (async)
(anonymous) @ production-app.js:152
Promise.then (async)
3898 @ production-app.js:38
f @ bootstrap:19
(anonymous) @ unsupportedIterableToArray.js:8
f.O @ chunk loaded:25
c @ jsonp chunk loading:84
(anonymous) @ framework-e12d22b6c31a0706d732.js:2
react-dom.production.min.js:216 Error: The result of this StaticQuery could not be fetched.

This is likely a bug in Gatsby and if refreshing the page does not fix it, please open an issue in https://github.com/gatsbyjs/gatsby/issues
    at p (gatsby-browser-entry.js:77:11)
    at c (Seo.tsx:20:22)
    at ro (react-dom.production.min.js:157:137)
    at Hu (react-dom.production.min.js:267:460)
    at Pi (react-dom.production.min.js:250:347)
    at _i (react-dom.production.min.js:250:278)
    at xi (react-dom.production.min.js:250:138)
    at vi (react-dom.production.min.js:243:163)
    at fi (react-dom.production.min.js:237:175)
    at Gi (react-dom.production.min.js:285:27)
uu @ react-dom.production.min.js:216
n.callback @ react-dom.production.min.js:216
fa @ react-dom.production.min.js:131
hu @ react-dom.production.min.js:220
Li @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wl @ react-dom.production.min.js:122
Ti @ react-dom.production.min.js:252
vi @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
Wl @ react-dom.production.min.js:122
Ql @ react-dom.production.min.js:123
Hl @ react-dom.production.min.js:122
yi @ react-dom.production.min.js:244
rs @ react-dom.production.min.js:289
t.hydrate @ react-dom.production.min.js:295
c @ production-app.js:209
(anonymous) @ production-app.js:221
setTimeout (async)
(anonymous) @ production-app.js:220
Promise.then (async)
(anonymous) @ production-app.js:152
Promise.then (async)
3898 @ production-app.js:38
f @ bootstrap:19
(anonymous) @ unsupportedIterableToArray.js:8
f.O @ chunk loaded:25
c @ jsonp chunk loading:84
(anonymous) @ framework-e12d22b6c31a0706d732.js:2
react-dom.production.min.js:123 Uncaught Error: The result of this StaticQuery could not be fetched.

This is likely a bug in Gatsby and if refreshing the page does not fix it, please open an issue in https://github.com/gatsbyjs/gatsby/issues
    at p (gatsby-browser-entry.js:77:11)
    at c (Seo.tsx:20:22)
    at ro (react-dom.production.min.js:157:137)
    at Hu (react-dom.production.min.js:267:460)
    at Pi (react-dom.production.min.js:250:347)
    at _i (react-dom.production.min.js:250:278)
    at xi (react-dom.production.min.js:250:138)
    at vi (react-dom.production.min.js:243:163)
    at fi (react-dom.production.min.js:237:175)
    at Gi (react-dom.production.min.js:285:27)
p @ gatsby-browser-entry.js:77
c @ Seo.tsx:20
ro @ react-dom.production.min.js:157
Hu @ react-dom.production.min.js:267
Pi @ react-dom.production.min.js:250
_i @ react-dom.production.min.js:250
xi @ react-dom.production.min.js:250
vi @ react-dom.production.min.js:243
fi @ react-dom.production.min.js:237
Gi @ react-dom.production.min.js:285
(anonymous) @ react-dom.production.min.js:289
yi @ react-dom.production.min.js:244
rs @ react-dom.production.min.js:289
t.hydrate @ react-dom.production.min.js:295
c @ production-app.js:209
(anonymous) @ production-app.js:221
setTimeout (async)
(anonymous) @ production-app.js:220
Promise.then (async)
(anonymous) @ production-app.js:152
Promise.then (async)
3898 @ production-app.js:38
f @ bootstrap:19
(anonymous) @ unsupportedIterableToArray.js:8
f.O @ chunk loaded:25
c @ jsonp chunk loading:84
(anonymous) @ framework-e12d22b6c31a0706d732.js:2
register-service-worker.js:19 installingWorker ServiceWorker {scriptURL: 'https://nivo.rocks/sw.js', state: 'installing', onstatechange: null, onerror: null}
PrecacheController.mjs:194 Uncaught (in promise) bad-precaching-response: bad-precaching-response :: [{"url":"https://nivo.rocks/offline-plugin-app-shell-fallback/index.html?__WB_REVISION__=272089189ffb7a285ca55525f7ce0d8e","status":404}]
    at l.o (https://nivo.rocks/workbox-v4.3.1/workbox-precaching.prod.js:1:1749)
    at async Promise.all (index 0)
    at async l.install (https://nivo.rocks/workbox-v4.3.1/workbox-precaching.prod.js:1:1221)
o @ PrecacheController.mjs:194
register-service-worker.js:50 The installing service worker became redundant.
```

**Comment by plouc** [comment]
Should be fixed, I had no issues loading it in Brave, but I must admit that's usually not a browser I check.

**Comment by matthewoates** [comment]
Same - no issues in brave on my device which previously reliably reproduced the issue.
