### ISSUE TITLE
Tooltip not functional with custom range

### ISSUE THREAD

**Issue by kdog1425** [plouc/nivo#2101]
When using customRange, customMeasure - we get this error when onMouseEnter fires (can be seen in the interactive component playground):
```
react-dom.development.js:4312 Uncaught TypeError: Cannot read properties of undefined (reading 'clientX')
    at hooks.ts:29:29
    at onMouseEnter (BulletItem.tsx:97:17)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4291:25)
    at executeDispatch (react-dom.development.js:9041:3)
    at processDispatchQueueItemsInOrder (react-dom.development.js:9073:7)
    at processDispatchQueue (react-dom.development.js:9086:5)
    at dispatchEventsForPlugins (react-dom.development.js:9097:3)
```

**Comment by kdog1425** [comment]
<img width="1421" alt="Screen Shot 2022-08-05 at 14 06 39" src="https://user-images.githubusercontent.com/5717512/183065201-201e161f-ebdc-49f6-90b3-f2aff37fc161.png">

**Comment by willemmulder** [comment]
Yes I have the same problem with a `ResponsiveBullet`. Did you find any workaround?

BTW: what I actually want is to change the mouseHover text of a measure. The goal is to show a custom text for every measure instead of the default number, but I couldn't figure out how to do that without a CustomMeasure (which then again, doesn't work due to this issue).

Thanks!

**Comment by Ashish-vora** [comment]
I am still getting this issue, Please give some solution for that, is any way to hide or disable the tooltip.

![Screenshot from 2023-03-16 22-09-46](https://user-images.githubusercontent.com/59089190/225690632-4b7c80ad-416c-4431-b173-821a571840ea.png)
