### ISSUE TITLE
Uncaught TypeError: Object(...) is not a function at e (nivo-bar)

### ISSUE THREAD

**Issue by MadhuTanakam** [plouc/nivo#2217]
**Thanks for using nivo**

Before creating an issue...

**Are you asking a question?**

Please don't file GitHub issues to ask questions.
Try to use the discord channel first: https://discord.gg/n7Ft74f.

**Describe/explain the bug**

**To Reproduce**
Please **include a test case that demonstrates the issue you're reporting on a platform like codesandbox**, I already have several existing examples on codesandbox, you can fork one of them
depending on the component you're working on: https://codesandbox.io/u/plouc/sandboxes.
This is very critical to maintainers in order to help us see the issue you're seeing.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

nivo-bar.es.js:1 Uncaught TypeError: Object(...) is not a function
    at e (nivo-bar.es.js:1:7659)
    at pe (nivo-bar.es.js:1:9410)
    at ye (nivo-bar.es.js:1:11798)
    at ke (nivo-bar.es.js:1:14480)
    at renderWithHooks (react-dom.development.js:14977:1)
    at mountIndeterminateComponent (react-dom.development.js:17803:1)
    at beginWork (react-dom.development.js:19041:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)

**Comment by abelmo** [comment]
i'm getting this issue as well 

`Uncaught TypeError: Object(...) is not a function
    at e (nivo-bar.es.js:464:1)
    at pe (nivo-bar.es.js:600:1)
    at ye (nivo-bar.es.js:733:1)
    at Ve (nivo-bar.es.js:1236:1)
    at renderWithHooks (react-dom.development.js:12980:1)
    at mountIndeterminateComponent (react-dom.development.js:15463:1)
    at beginWork (react-dom.development.js:16517:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3555:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3599:1)`

**Comment by plouc** [comment]
Unless there's a test case demonstrating the issue, I don't think we can help with this issue, closing for now, if you can provide some, I'll reopen.
