### ISSUE TITLE
RangeError: Maximum call stack size exceeded on build after installing @nivo/radial-bar": "^0.83.0 

### ISSUE THREAD

**Issue by LironHazan** [plouc/nivo#2353]
Hey!
I just started to use Nivo :) and not sure why, but after installing:
`@nivo/radial-bar": "^0.83.0"`
I cannot bundle to prod with vite, getting a tsc error,
it didn't happen when installed  
`"@nivo/line": "^0.83.0",`
I also have
```
        "@nivo/bar": "^0.83.0",
        "@nivo/core": "^0.83.0",
```

```
> tsc && cross-env NODE_OPTIONS=--max-old-space-size=8192 P_ENV=production vite build

/Users/lironhazan/dev/cloud-apps/services/dashboard/client/node_modules/typescript/lib/tsc.js:96888
                throw e;
                ^

RangeError: Maximum call stack size exceeded
    at Object.isPartOfTypeNode (/Users/lironhazan/dev/cloud-apps/services/dashboard/client/node_modules/typescript/lib/tsc.js:11786:30)
    at containsReference (/Users/lironhazan/dev/cloud-apps/services/dashboard/client/node_modules/typescript/lib/tsc.js:52596:53)
    at visitNode (/Users/lironhazan/dev/cloud-apps/services/dashboard/client/node_modules/typescript/lib/tsc.js:24472:24)
    at Object.forEachChild (/Users/lironhazan/dev/cloud-apps/services/dashboard/client/node_modules/typescript/lib/tsc.js:24621:24)
    at containsReference (/Users/lironhazan/dev/cloud-apps/services/dashboard/client/node_modules/typescript/lib/tsc.js:52607:29)
    at visitNode (/Users/lironhazan/dev/cloud-apps/services/dashboard/client/node_modules/typescript/lib/tsc.js:24472:24)
    at Object.forEachChild (/Users/lironhazan/dev/cloud-apps/services/dashboard/client/node_modules/typescript/lib/tsc.js:24657:24)
    at containsReference (/Users/lironhazan/dev/cloud-apps/services/dashboard/client/node_modules/typescript/lib/tsc.js:52607:29)
    at visitNode (/Users/lironhazan/dev/cloud-apps/services/dashboard/client/node_modules/typescript/lib/tsc.js:24472:24)
    at Object.forEachChild (/Users/lironhazan/dev/cloud-apps/services/dashboard/client/node_modules/typescript/lib/tsc.js:24640:24)


```

using typescript version:  "typescript": "^4.5.4",
npm 8.19.3 + node v16.19.1

Will really appreciate any advice

**Comment by LironHazan** [comment]
@plouc Hey I hope it's ok I'm tagging you, appreciate your effort,
Do you have any lead on why this could happen?

**Comment by echarles** [comment]
Same issue here with compiling with tsc. Works fine with webpack devserver but fails when with tsc. Will need to look to another lib for now...

**Comment by plouc** [comment]
@LironHazan, I don't know what could cause that, it would need to be investigated.

**Comment by LironHazan** [comment]
Thanks, I'm looking into more charts of Nivo, will update if see more issues of if I'll have a lead of the root cause

**Comment by LironHazan** [comment]
@plouc impressive work on the make file! :)
I've tried to look into the way the lib is built and couldn't find mention to any active typechecking in the rollup config,
I'm not an expert in rollup but maybe using `@rollup/plugin-typescript` would add the typechecking phase and help tracing such issues?

**Comment by Xantier** [comment]
This looks to be introduced somewhere in version 0.81.0. 
Dependencies 
```
    "@nivo/bar": "^0.80.0",
    "@nivo/core": "^0.80.0",
    "@nivo/pie": "^0.80.0",
```    

Compile properly, though additional type dev dependencies need to be added in:
```
    "@types/d3-scale": "^4.0.3",
    "@types/d3-color": "^3.1.0",
    "@types/d3-scale-chromatic": "^3.0.0",
```

Bumping `@nivo/` deps to 0.81.0, we'll hit the typescript error (due to some introduced recursive typing?)

**Comment by LironHazan** [comment]
@Xantier I can't downgrade, it causes other conflicts in the project
Any chart with arcs has the issue, so far we tested: 
 
Pie Chart 
Sunburst Chart
Radial Bar Chart

**Comment by benellatalon** [comment]
The errors seems to be coming from `@nivo/arcs`

**Comment by plouc** [comment]
> @plouc impressive work on the make file! :) I've tried to look into the way the lib is built and couldn't find mention to any active typechecking in the rollup config, I'm not an expert in rollup but maybe using `@rollup/plugin-typescript` would add the typechecking phase and help tracing such issues?

Thank you 😊 The type checking is done via `pkgs-types`, and it's run on CI via:

```
pkgs-build: pkgs-types ##@1 packages build all packages
```

Initially `@rollup/plugin-typescript` didn't support type checking, that's why I used another approach.

**Comment by Xantier** [comment]
Here is a minimal reproduction: https://github.com/Xantier/nivo-ts-stackoverflow

**Comment by Xantier** [comment]
Flipping around version on the minimal reproduction, this actually looks to work on `0.81.0` version as well. `0.82.x` doesn't build at all so my assumption is that the issue was introduced for 83

**Comment by Jule-** [comment]
Hi, same issue here.

I have debugged `tsc` and it crashes when evaluating this file: `@nivo/arcs/dist/types/centers.d.ts`.

In fact, when you look at it there is a loooooot of import stuff from `@react-spring/*`, I am pretty sure this is what is killing the stack.

Can you see a quick fix or workaround for this? :grimacing:

**Comment by Jule-** [comment]
I think this issue appears due to: #2280 (released in [v0.82.0](https://github.com/plouc/nivo/releases/tag/v0.82.0))

**Comment by Jule-** [comment]
Unfortunately downgrading `@react-spring/web@9.4.5` is not enough, maybe a false lead... I think the generation of the `centers.d.ts` file should be responsible for this issue.

https://github.com/plouc/nivo/blob/2671ca4df614190f597bb63030bb794d3106c36e/packages/arcs/src/centers.ts#L54-L72

Maybe if you can type the `transition` property with a less wordy type than the one generated it could help `tsc` to compile. And I am not sure if/how we should report this to the `@react-spring/web` project.

**Comment by Jule-** [comment]
Same issue here:

https://github.com/plouc/nivo/blob/2671ca4df614190f597bb63030bb794d3106c36e/packages/arcs/src/useArcsTransition.ts#L21-L39

**Comment by Jule-** [comment]
bump

**Comment by acrylicode** [comment]
The issue is still there. For anyone interested, I deleted the types folder before running the tsc and it works.
So under node_modules/@nivo/bar there is a types folder. Just delete that. Do the same for all the charts you are using. If you want to get fancy you can wrap the tsc in another command that automatically deletes the types, executes tsc and then reinstalls it again.

**Comment by HendrikGrobler** [comment]
Bump. This issue is prevent us from using Nivo.

**Comment by ashwin-gairola** [comment]
@plouc This issue still exists even for `@nivo/bar`. Providing a large data array is causing `ResponsiveBar` and `ResponsiveBarCanvas` to break with the same error message. Can you please address this?

**Comment by AdamJPcars** [comment]
I am also having the same issue, i noticed that when i delete the "keys" prop, the chart get displayed with empty y-axis data. but if i remove any other prop it still gives me the error en breaks the applications. In that case it might have something to do with the keys prop.

This issue is quite blocking and should be fixed asap, since the point of this library is to show big sets of data.

**Comment by plouc** [comment]
A _good_ thing is that I can reproduce this issue on the nivo repo, using `"skipLibCheck": false,`, if I try to generate the types for the `@nivo/pie` package (`make pkg-types-pie`), I get the same error. Same for:

- `@nivo/sunburst`
- `@nivo/polar-axes`
- `@nivo/radial-bar`
- `@nivo/polar-bar`

So, it's probably related to `@nivo/arcs`, which passes (`make pkg-types-arcs`).

As already reported, the problem seems to be in `useArcCentersTransition` and `useArcsTransition`, both use a generic type.

I don't have a fix yet.
