### ISSUE TITLE
Line Graph - Cannot read from undefined property (reading 'x') when useMesh is enabled.

### ISSUE THREAD

**Issue by rob-cleeia** [plouc/nivo#2630]
**Describe/explain the bug**
We're using Nivo/Line (responsive) to render some line graphs. The data we use is nondeterministic, so we validate the data before we send it to the graph. Based on the documentation (here: https://nivo.rocks/line/), we use the following type for line graph data:

```typescript
interface line {
    id:   string | number;
    data: {
        x: number | string | Date
        y: number | string | Date
    }[]
}[]
```

However, we've recently noticed that if we have the `x` axis as a `number` and the `y` axis as a `string`, with `useMesh` enabled, it throws a client side exception.

**To Reproduce**
Render a Nivo/Line Graph with `useMesh` enabled, with data containing `x` axis as a number, and `y` axis as a string. EG:
```typescript
import React from 'react';
import { ResponsiveLine } from '@nivo/line';

export const LineGraph: React.FC = () => (
  <div style={{ height: '20rem' }}>
    <ResponsiveLine
      data={[
        {
          id: '1',
          label: 'Joe Biden',
          data: [
            {
              x: 1973,
              y: 'Senator',
            },
            {
              x: 2009,
              y: 'Vice President',
            },
            {
              x: 2017,
              y: 'End of Vice Presidency',
            },
            {
              x: 2021,
              y: 'President',
            },
          ],
        },
      ]}
      useMesh
    />
  </div>
);
export default LineGraph;

```

Steps to reproduce the behaviour:
1. Load above component.
2. Hover mouse over Line Graph

**Expected behaviour**
Should not cause a client side error.

**Screenshots**
Chrome:
![Screenshot 2024-08-08 at 12 00 12](https://github.com/user-attachments/assets/140ee2c1-d1a5-40f6-b64b-b60bd53f2a42)
FireFox:
![Screenshot 2024-08-08 at 12 02 56](https://github.com/user-attachments/assets/82b10604-84da-4941-8301-5e49289b4237)

**Desktop (please complete the following information - Not sure if this at all relevant, but okay):**
 - OS: MacOS 14.5
 - Browser: Chrome v127.0.6533.73
 - Browser: FireFox v115.13.0esr (64-bit)

**Additional context**
- We've disabled line-graphs on the website for now, as the data we receive is nondeterministic.
- The error text in chrome is as follows:
  ```log
  nivo-line.es.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'x')
      at nivo-line.es.js:1:1
      at renderWithHooks (react-dom.development.js:11121:1)
      at updateFunctionComponent (react-dom.development.js:16290:1)
      at beginWork$1 (react-dom.development.js:18472:1)
      at HTMLUnknownElement.callCallback (react-dom.development.js:20565:1)
      at Object.invokeGuardedCallbackImpl (react-dom.development.js:20614:1)
      at invokeGuardedCallback (react-dom.development.js:20689:1)
      at beginWork (react-dom.development.js:26949:1)
      at performUnitOfWork (react-dom.development.js:25748:1)
      at workLoopSync (react-dom.development.js:25464:1)
  ```
- I asked this on Discord, and never got an answer.
  1. https://discord.com/channels/358204068931567619/358204068931567620/1271054826637365248

**Comment by CTX-Rachel** [comment]
I had the same problem, when temporarily removing LineChart everything was fine.

**Comment by diego9497** [comment]
This issue is happening to me when the data is empty ([]) and I hover mouse over the graph, when there is data is working fine.
I'm upgrading from 0.79.1 to 0.88.0, it was working fine in the old version.

[Codesandbox](https://codesandbox.io/p/sandbox/x2jgqy?file=%2Fsrc%2FApp.tsx%3A27%2C17&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm3yxu7cz00063b6pfggotsop%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm3yxu7cz00023b6pzai7f8pu%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm3yxu7cz00033b6piju2jjcc%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm3yxu7cz00053b6pjheif71x%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm3yxu7cz00023b6pzai7f8pu%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm3yxu7cy00013b6pbikjfblr%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%257D%255D%252C%2522id%2522%253A%2522cm3yxu7cz00023b6pzai7f8pu%2522%252C%2522activeTabId%2522%253A%2522cm3yxu7cy00013b6pbikjfblr%2522%257D%252C%2522cm3yxu7cz00053b6pjheif71x%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm3yxu7cz00043b6ptkhuwoxc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cm3yxu7cz00053b6pjheif71x%2522%252C%2522activeTabId%2522%253A%2522cm3yxu7cz00043b6ptkhuwoxc%2522%257D%252C%2522cm3yxu7cz00033b6piju2jjcc%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cm3yxu7cz00033b6piju2jjcc%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by olgacara** [comment]
bump

**Comment by rob-cleeia** [comment]
This issue is still present, and was broken in a release. Can someone take a look, rather than just ignoring it and hoping we go away?

**Comment by plouc** [comment]
> This issue is happening to me when the data is empty ([]) and I hover mouse over the graph, when there is data is working fine. I'm upgrading from 0.79.1 to 0.88.0, it was working fine in the old version.

The empty data issue was solved by #2669.

**Comment by plouc** [comment]
> This issue is still present, and was broken in a release. Can someone take a look, rather than just ignoring it and hoping we go away?

@rob-cleeia, that's such a weird comment...

Now regarding your issue, the problem is that the default `yScale` used for the chart is a linear scale, which isn't suited for string values, you might want to use a point scale for example, like this: `yScale={{ type: 'point' }}`.
